const series = [
  { title: "아키텍쳐" },
  { title: "배트맨™" },
  { title: "브릭헤즈" },
  { title: "브릭 스케치™" },
  { title: "시티" },
  { title: "클래식" },
  { title: "크리에이터 3-in-1" },
  { title: "크리에이터 엑스퍼트" },
  { title: "DC" },
  { title: "디즈니™" },

  { title: "디즈니 미키와 친구들" },
  { title: "도트" },
  { title: "듀플로®" },
  { title: "프렌즈" },
  { title: "겨울왕국" },
  { title: "해리포터™" },
  { title: "아이디어" },
  { title: "쥬라기 월드™" },
  { title: "레고® 아트" },
  { title: "레고® 에듀케이션" },

  { title: "레고® 슈퍼 마리오™" },
  { title: "마블" },
  { title: "마인드스톰®" },
  { title: "마인크래프트®" },
  { title: "미니피겨" },
  { title: "미니언즈" },
  { title: "몽키 키드™" },
  { title: "닌자고™" },
  { title: "오버워치" },
  { title: "파워펑션" },

  { title: "파워드업" },
  { title: "파워퍼프걸™" },
  { title: "스피드 챔피언" },
  { title: "스파이더맨" },
  { title: "스타워즈™" },
  { title: "기묘한 이야기" },
  { title: "테크닉" },
  { title: "트롤 월드 투어" },
  { title: "비디요™" },
];

export default series;
