export const series = [
  { id: 1, title: "아키텍쳐" },
  { id: 1, title: "배트맨™" },
  { id: 1, title: "브릭헤즈" },
  { id: 1, title: "브릭 스케치™" },
  { id: 1, title: "시티" },
  { id: 1, title: "클래식" },
  { id: 1, title: "크리에이터 3-in-1" },
  { id: 1, title: "크리에이터 엑스퍼트" },
  { id: 1, title: "DC" },
  { id: 1, title: "디즈니™" },

  { id: 1, title: "디즈니 미키와 친구들" },
  { id: 1, title: "도트" },
  { id: 1, title: "듀플로®" },
  { id: 1, title: "프렌즈" },
  { id: 1, title: "겨울왕국" },
  { id: 1, title: "해리포터™" },
  { id: 1, title: "아이디어" },
  { id: 1, title: "쥬라기 월드™" },
  { id: 1, title: "레고® 아트" },
  { id: 1, title: "레고® 에듀케이션" },

  { id: 2, title: "레고® 슈퍼 마리오™" },
  { id: 2, title: "마블" },
  { id: 2, title: "마인드스톰®" },
  { id: 2, title: "마인크래프트®" },
  { id: 2, title: "미니피겨" },
  { id: 2, title: "미니언즈" },
  { id: 2, title: "몽키 키드™" },
  { id: 2, title: "닌자고™" },
  { id: 2, title: "오버워치" },
  { id: 2, title: "파워펑션" },

  { id: 2, title: "파워드업" },
  { id: 2, title: "파워퍼프걸™" },
  { id: 2, title: "스피드 챔피언" },
  { id: 2, title: "스파이더맨" },
  { id: 2, title: "스타워즈™" },
  { id: 2, title: "기묘한 이야기" },
  { id: 2, title: "테크닉" },
  { id: 2, title: "트롤 월드 투어" },
  { id: 2, title: "비디요™" },
];

export const interest = [
  { id: 1, title: "성인 환영" },
  { id: 1, title: "동물" },
  { id: 1, title: "미술과 공예" },
  { id: 1, title: "빌딩" },
  { id: 1, title: "자동차" },
  { id: 1, title: "아이들을 위한 코딩 학습" },
  { id: 1, title: "드래곤" },
  { id: 1, title: "판타지" },
  { id: 1, title: "영화" },
  { id: 1, title: "Gaming" },

  { id: 1, title: "초기 학습용 조립" },
  { id: 1, title: "음악" },
  { id: 1, title: "닌자" },
  { id: 1, title: "유아용" },
  { id: 1, title: "공주" },
  { id: 1, title: "현실 세계의 영웅들" },
  { id: 1, title: "아동용 로봇" },
  { id: 1, title: "시즌상품" },
  { id: 1, title: "우주" },
  { id: 1, title: "스포츠" },

  { id: 2, title: "STEM" },
  { id: 2, title: "기차" },
  { id: 2, title: "여행" },
  { id: 2, title: "TV 프로그램" },
  { id: 2, title: "차량" },
];

export const 테스트 = [
  { id: 1, title: "초기 학습용 조립" },
  { id: 1, title: "음악" },
  { id: 1, title: "닌자" },
  { id: 1, title: "유아용" },
  { id: 1, title: "공주" },
  { id: 1, title: "현실 세계의 영웅들" },
  { id: 1, title: "아동용 로봇" },
  { id: 1, title: "시즌상품" },
  { id: 1, title: "우주" },
  { id: 1, title: "스포츠" },

  { id: 2, title: "STEM" },
  { id: 2, title: "기차" },
  { id: 2, title: "여행" },
  { id: 2, title: "TV 프로그램" },
  { id: 2, title: "차량" },
];
